language: c

os: linux
dist: trusty


compiler: arm-none-eabi-gcc


before_install:
  -  sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  -  sudo apt-get update -q
  -  sudo apt-get install gcc-arm-embedded -y


script:
  -  make -j2 -C targets/Cloud_STM32F429IGTx_FIRE/GCC
  -  make -j2 -C targets/Mini_Project/cortex-m0plus_without_driver/GCC
  -  make -j2 -C targets/Mini_Project/cortex-m3_without_driver/GCC
  -  make -j2 -C targets/Mini_Project/cortex-m4_without_driver/GCC
  -  make -j2 -C targets/NXP_LPC51U68/GCC
  -  make -j2 -C targets/STM32F103VET6_NB_GCC/GCC
  -  make -j2 -C targets/STM32L431RxTx_IoTClub/GCC
  -  make -j2 -C targets/IoTClub-EVB-L1/GCC
